name: building
on: [push,workflow_dispatch]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "good morning Team"
  deloying:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        run: echo "good bye team!KJ;.gh,!"
      
